# Generated by Django 4.0 on 2022-01-08 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_user_id_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id_admin',
            new_name='is_admin',
        ),
    ]
